title: <p align = "center"> Sudeep Menon" </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/sudeepvmenon/">LinkedIn</a> |
  <a href="https://github.com/sudeepvmenon">GitHub</a>
  
  <br>   
  I'm working on Principal Analyst at D.E.Shaw.
  <br>
  </p>



theme: jekyll-theme-minimal
